### ISSUE TITLE
URLs can't contain certain characters

### ISSUE THREAD

**Issue by tylerbhughes** [OpenHuntsville/hntsvll#128]
Adding certain characters like a period in the profile URL prevents you from accessing your profile and your profile edit page. To prevent this we should test and determine which characters can't be used in the URL. Then add a RegEx to validate the profile URL field before submitting and throw an alert message if there is a problem. We should also put some type of message near the input field letting people know what characters are allowed.

**Comment by chrisbeaman** [comment]
Can we make this easier on ourselves and just make it so that only letters and
numbers are allowed, with helper text to explain this?  





On Thu, Feb 23, 2017 10:55 PM, Tyler Hughes notifications@github.com  wrote:
Adding certain characters like a period in the profile URL prevents you from
accessing your profile and your profile edit page. To prevent this we should
test and determine which characters can't be used in the URL. Then add a RegEx
to validate the profile URL field before submitting and throw an alert message
if there is a problem. We should also put some type of message near the input
field letting people know what characters are allowed.

**Comment by davidhjones** [comment]
That seems like a valid solution for now

**Comment by davidhjones** [comment]
@RandomlyKnighted I figured this would be a good one for you since it doesn't involve much Pakyow. All of this logic should be on the front-end utilizing jQuery

**Comment by skylenewman** [comment]
At some point, it would be nice to mirror the validation on the back end.

**Comment by davidhjones** [comment]
Very true. We should be doing this everywhere TBH.

**Comment by davidhjones** [comment]
Needs more work for Safari. The pattern field doesn't work on Safari.

**Comment by davidhjones** [comment]
@RandomlyKnighted I forgot to mention that we **should** allow dashes.

**Comment by tylerbhughes** [comment]
As of Safari 10.1 the pattern attribute is now supported. I've tested it and it's working fine with version 10.1.2. I'll update the input for the profile url so that it only allows numbers, letters and hyphens.
